<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.joineryhq.jentitylink/xml/schema/CRM/Jentitylink/jentitylinkOp.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:48972cddad0ef60ca3078d61c059ebfd)
 */
use CRM_Jentitylink_ExtensionUtil as E;

/**
 * Database access object for the JentitylinkOp entity.
 */
class CRM_Jentitylink_DAO_JentitylinkOp extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_jentitylink_op';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique JentitylinkOp ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to jentitylink
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $jentitylink_id;

  /**
   * e.g. view.contact.activity
   *
   * @var string|null
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $op;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_jentitylink_op';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Jentitylink Ops') : E::ts('Jentitylink Op');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'jentitylink_id', 'civicrm_jentitylink', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique JentitylinkOp ID'),
          'required' => TRUE,
          'where' => 'civicrm_jentitylink_op.id',
          'table_name' => 'civicrm_jentitylink_op',
          'entity' => 'JentitylinkOp',
          'bao' => 'CRM_Jentitylink_DAO_JentitylinkOp',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'jentitylink_id' => [
          'name' => 'jentitylink_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Jentitylink ID'),
          'description' => E::ts('FK to jentitylink'),
          'required' => TRUE,
          'where' => 'civicrm_jentitylink_op.jentitylink_id',
          'table_name' => 'civicrm_jentitylink_op',
          'entity' => 'JentitylinkOp',
          'bao' => 'CRM_Jentitylink_DAO_JentitylinkOp',
          'localizable' => 0,
          'FKClassName' => 'CRM_Jentitylink_DAO_Jentitylink',
          'add' => NULL,
        ],
        'op' => [
          'name' => 'op',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Op'),
          'description' => E::ts('e.g. view.contact.activity'),
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_jentitylink_op.op',
          'table_name' => 'civicrm_jentitylink_op',
          'entity' => 'JentitylinkOp',
          'bao' => 'CRM_Jentitylink_DAO_JentitylinkOp',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'jentitylink_op', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'jentitylink_op', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
