-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_jentitylink_op`;
DROP TABLE IF EXISTS `civicrm_jentitylink`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_jentitylink
-- *
-- * Links configured by Joinery Entity Links extension
-- *
-- *******************************************************/
CREATE TABLE `civicrm_jentitylink` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Jentitylink ID',
  `entity_name` varchar(64) COMMENT 'e.g. \"Contact\"',
  `entity_type` varchar(64) COMMENT 'e.g. \"Individual\"',
  `entity_sub_type` varchar(64) COMMENT 'e.g. \"Student\"',
  `permission` varchar(128) COMMENT 'require this permisison to display the link',
  `name` varchar(255) COMMENT 'user-visible link text',
  `title` varchar(255) COMMENT 'link title attribute',
  `url` varchar(255) COMMENT 'link url',
  `qs` varchar(255) COMMENT 'link query string',
  `class` varchar(255) COMMENT 'link class attribute',
  `weight` int unsigned COMMENT 'link weight/order',
  PRIMARY KEY (`id`)
)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_jentitylink_op
-- *
-- * Relevant op value for Joinery Entity Links
-- *
-- *******************************************************/
CREATE TABLE `civicrm_jentitylink_op` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique JentitylinkOp ID',
  `jentitylink_id` int unsigned COMMENT 'FK to jentitylink',
  `op` varchar(255) COMMENT 'e.g. view.contact.activity',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_jentitylink_op_jentitylink_id FOREIGN KEY (`jentitylink_id`) REFERENCES `civicrm_jentitylink`(`id`) ON DELETE CASCADE
)
ENGINE=InnoDB;
